<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260611120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Separate persistent device trust and blocking state from user sessions';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();

        if ($platform === 'mysql') {
            $this->addSql("CREATE TABLE user_device (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, device_id VARCHAR(64) NOT NULL, device_name VARCHAR(255) DEFAULT NULL, user_agent VARCHAR(1000) DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', last_seen_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', trusted_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', trust_expires_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', revoked_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', revoked_reason VARCHAR(100) DEFAULT NULL, blocked_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', blocked_reason VARCHAR(255) DEFAULT NULL, INDEX IDX_6C7DADB3A76ED395 (user_id), INDEX idx_user_device_identifier (device_id), UNIQUE INDEX uniq_user_device_identifier (user_id, device_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
            $this->addSql('ALTER TABLE user_device ADD CONSTRAINT FK_6C7DADB3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
            $this->addSql("
                INSERT INTO user_device (
                    user_id, device_id, device_name, user_agent, ip_address,
                    created_at, last_seen_at, trusted_at, trust_expires_at,
                    revoked_at, revoked_reason, blocked_at, blocked_reason
                )
                SELECT
                    latest.user_id,
                    latest.device_id,
                    latest.device_name,
                    latest.user_agent,
                    latest.ip_address,
                    latest.created_at,
                    latest.last_activity_at,
                    latest.created_at,
                    DATE_ADD(latest.last_activity_at, INTERVAL 90 DAY),
                    CASE
                        WHEN latest.is_revoked = 1 AND COALESCE(latest.revoked_reason, '') <> 'logout'
                        THEN COALESCE(latest.revoked_at, latest.last_activity_at)
                        ELSE NULL
                    END,
                    CASE
                        WHEN latest.is_revoked = 1 AND COALESCE(latest.revoked_reason, '') <> 'logout'
                        THEN latest.revoked_reason
                        ELSE NULL
                    END,
                    CASE WHEN latest.is_blocked = 1 THEN COALESCE(latest.blocked_at, latest.last_activity_at) ELSE NULL END,
                    CASE WHEN latest.is_blocked = 1 THEN latest.blocked_reason ELSE NULL END
                FROM (
                    SELECT
                        s.*,
                        ROW_NUMBER() OVER (
                            PARTITION BY s.user_id, s.device_id
                            ORDER BY s.created_at DESC, s.id DESC
                        ) AS rn
                    FROM user_session s
                    WHERE s.device_id IS NOT NULL
                ) latest
                WHERE latest.rn = 1
            ");

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql('CREATE TABLE user_device (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, device_id VARCHAR(64) NOT NULL, device_name VARCHAR(255) DEFAULT NULL, user_agent VARCHAR(1000) DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trusted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trust_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_reason VARCHAR(100) DEFAULT NULL, blocked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, blocked_reason VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_6C7DADB3A76ED395 ON user_device (user_id)');
            $this->addSql('CREATE INDEX idx_user_device_identifier ON user_device (device_id)');
            $this->addSql('CREATE UNIQUE INDEX uniq_user_device_identifier ON user_device (user_id, device_id)');
            $this->addSql('ALTER TABLE user_device ADD CONSTRAINT FK_6C7DADB3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql("
                INSERT INTO user_device (
                    user_id, device_id, device_name, user_agent, ip_address,
                    created_at, last_seen_at, trusted_at, trust_expires_at,
                    revoked_at, revoked_reason, blocked_at, blocked_reason
                )
                SELECT
                    latest.user_id,
                    latest.device_id,
                    latest.device_name,
                    latest.user_agent,
                    latest.ip_address,
                    latest.created_at,
                    latest.last_activity_at,
                    latest.created_at,
                    latest.last_activity_at + INTERVAL '90 days',
                    CASE
                        WHEN latest.is_revoked = TRUE AND COALESCE(latest.revoked_reason, '') <> 'logout'
                        THEN COALESCE(latest.revoked_at, latest.last_activity_at)
                        ELSE NULL
                    END,
                    CASE
                        WHEN latest.is_revoked = TRUE AND COALESCE(latest.revoked_reason, '') <> 'logout'
                        THEN latest.revoked_reason
                        ELSE NULL
                    END,
                    CASE WHEN latest.is_blocked = TRUE THEN COALESCE(latest.blocked_at, latest.last_activity_at) ELSE NULL END,
                    CASE WHEN latest.is_blocked = TRUE THEN latest.blocked_reason ELSE NULL END
                FROM (
                    SELECT
                        s.*,
                        ROW_NUMBER() OVER (
                            PARTITION BY s.user_id, s.device_id
                            ORDER BY s.created_at DESC, s.id DESC
                        ) AS rn
                    FROM user_session s
                    WHERE s.device_id IS NOT NULL
                ) latest
                WHERE latest.rn = 1
            ");

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();

        if ($platform === 'mysql') {
            $this->addSql('ALTER TABLE user_device DROP FOREIGN KEY FK_6C7DADB3A76ED395');
            $this->addSql('DROP TABLE user_device');

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql('DROP TABLE user_device');

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }
}
