<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260407120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user_subscription table and backfill current Stripe-linked users';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();

        if ($platform === 'mysql') {
            $this->addSql('CREATE TABLE user_subscription (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, stripe_customer_id VARCHAR(255) DEFAULT NULL, stripe_subscription_id VARCHAR(255) DEFAULT NULL, status VARCHAR(50) DEFAULT NULL, plan_code VARCHAR(50) DEFAULT NULL, is_active TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX uniq_user_subscription_user (user_id), UNIQUE INDEX uniq_user_subscription_customer (stripe_customer_id), UNIQUE INDEX uniq_user_subscription_subscription (stripe_subscription_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('ALTER TABLE user_subscription ADD CONSTRAINT FK_3E7B02A5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
            $this->addSql('INSERT INTO user_subscription (user_id, stripe_customer_id, stripe_subscription_id, status, plan_code, is_active, created_at, updated_at)
                SELECT u.id, u.stripe_customer_id, u.stripe_subscription_id, CASE WHEN u.is_subscribed = 1 THEN \'active\' ELSE NULL END, \'pro\', u.is_subscribed, NOW(), NOW()
                FROM user u
                WHERE (u.stripe_customer_id IS NOT NULL OR u.stripe_subscription_id IS NOT NULL OR u.is_subscribed = 1)
                AND NOT EXISTS (
                    SELECT 1 FROM user_subscription us WHERE us.user_id = u.id
                )');

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql('CREATE TABLE user_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, stripe_customer_id VARCHAR(255) DEFAULT NULL, stripe_subscription_id VARCHAR(255) DEFAULT NULL, status VARCHAR(50) DEFAULT NULL, plan_code VARCHAR(50) DEFAULT NULL, is_active BOOLEAN DEFAULT FALSE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX uniq_user_subscription_user ON user_subscription (user_id)');
            $this->addSql('CREATE UNIQUE INDEX uniq_user_subscription_customer ON user_subscription (stripe_customer_id)');
            $this->addSql('CREATE UNIQUE INDEX uniq_user_subscription_subscription ON user_subscription (stripe_subscription_id)');
            $this->addSql('ALTER TABLE user_subscription ADD CONSTRAINT FK_3E7B02A5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('INSERT INTO user_subscription (user_id, stripe_customer_id, stripe_subscription_id, status, plan_code, is_active, created_at, updated_at)
                SELECT u.id, u.stripe_customer_id, u.stripe_subscription_id, CASE WHEN u.is_subscribed = TRUE THEN \'active\' ELSE NULL END, \'pro\', u.is_subscribed, NOW(), NOW()
                FROM "user" u
                WHERE (u.stripe_customer_id IS NOT NULL OR u.stripe_subscription_id IS NOT NULL OR u.is_subscribed = TRUE)
                AND NOT EXISTS (
                    SELECT 1 FROM user_subscription us WHERE us.user_id = u.id
                )');

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();

        if ($platform === 'mysql') {
            $this->addSql('ALTER TABLE user_subscription DROP FOREIGN KEY FK_3E7B02A5A76ED395');
            $this->addSql('DROP TABLE user_subscription');

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql('DROP TABLE user_subscription');

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }
}
