<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260818150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add backward-compatible extension onboarding and one-time pairing challenges';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();

        if ($platform === 'mysql') {
            $this->addSql("ALTER TABLE user ADD extension_onboarding_status VARCHAR(20) DEFAULT 'completed' NOT NULL, ADD extension_onboarded_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)'");
            $this->addSql("CREATE TABLE extension_pairing_challenge (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, public_id VARCHAR(36) NOT NULL, token_hash VARCHAR(64) NOT NULL, client_id VARCHAR(128) NOT NULL, status VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', expires_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', exchanged_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', completed_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_EXT_PAIRING_PUBLIC_ID (public_id), UNIQUE INDEX UNIQ_EXT_PAIRING_TOKEN_HASH (token_hash), INDEX IDX_EXT_PAIRING_USER (user_id), INDEX idx_extension_pairing_client (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
            $this->addSql('ALTER TABLE extension_pairing_challenge ADD CONSTRAINT FK_EXT_PAIRING_USER FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql("ALTER TABLE \"user\" ADD extension_onboarding_status VARCHAR(20) DEFAULT 'completed' NOT NULL, ADD extension_onboarded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
            $this->addSql('CREATE TABLE extension_pairing_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, public_id VARCHAR(36) NOT NULL, token_hash VARCHAR(64) NOT NULL, client_id VARCHAR(128) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, exchanged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_EXT_PAIRING_PUBLIC_ID ON extension_pairing_challenge (public_id)');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_EXT_PAIRING_TOKEN_HASH ON extension_pairing_challenge (token_hash)');
            $this->addSql('CREATE INDEX IDX_EXT_PAIRING_USER ON extension_pairing_challenge (user_id)');
            $this->addSql('CREATE INDEX idx_extension_pairing_client ON extension_pairing_challenge (client_id)');
            $this->addSql('ALTER TABLE extension_pairing_challenge ADD CONSTRAINT FK_EXT_PAIRING_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();

        if ($platform === 'mysql') {
            $this->addSql('ALTER TABLE extension_pairing_challenge DROP FOREIGN KEY FK_EXT_PAIRING_USER');
            $this->addSql('DROP TABLE extension_pairing_challenge');
            $this->addSql('ALTER TABLE user DROP extension_onboarding_status, DROP extension_onboarded_at');

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql('DROP TABLE extension_pairing_challenge');
            $this->addSql('ALTER TABLE "user" DROP extension_onboarding_status, DROP extension_onboarded_at');

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }
}
