<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260820150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add safe Stripe Sandbox/Production mode selection and billing mode audit fields';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();

        if ($platform === 'mysql') {
            $this->addSql("ALTER TABLE user_subscription ADD stripe_mode VARCHAR(20) DEFAULT 'production' NOT NULL");
            $this->addSql("ALTER TABLE stripe_webhook_event ADD stripe_mode VARCHAR(20) DEFAULT 'production' NOT NULL");
            $this->addSql("CREATE TABLE stripe_payment_configuration (id INT AUTO_INCREMENT NOT NULL, active_mode VARCHAR(20) NOT NULL, updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_by VARCHAR(180) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql("ALTER TABLE user_subscription ADD stripe_mode VARCHAR(20) DEFAULT 'production' NOT NULL");
            $this->addSql("ALTER TABLE stripe_webhook_event ADD stripe_mode VARCHAR(20) DEFAULT 'production' NOT NULL");
            $this->addSql('CREATE TABLE stripe_payment_configuration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, active_mode VARCHAR(20) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_by VARCHAR(180) DEFAULT NULL, PRIMARY KEY(id))');
            $this->addSql("COMMENT ON COLUMN stripe_payment_configuration.updated_at IS '(DC2Type:datetime_immutable)'");

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE stripe_payment_configuration');
        $this->addSql('ALTER TABLE user_subscription DROP stripe_mode');
        $this->addSql('ALTER TABLE stripe_webhook_event DROP stripe_mode');
    }
}
