<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260819120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add password reveal permissions to direct and team credential shares';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();

        if ($platform === 'mysql') {
            $this->addSql('ALTER TABLE shared_access ADD can_reveal_password TINYINT(1) DEFAULT 1 NOT NULL');
            $this->addSql('CREATE TABLE team_credential_permission (id INT AUTO_INCREMENT NOT NULL, team_id INT NOT NULL, credential_id INT NOT NULL, can_reveal_password TINYINT(1) DEFAULT 1 NOT NULL, INDEX IDX_TEAM_CREDENTIAL_PERMISSION_TEAM (team_id), INDEX IDX_TEAM_CREDENTIAL_PERMISSION_CREDENTIAL (credential_id), UNIQUE INDEX uniq_team_credential_permission (team_id, credential_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('ALTER TABLE team_credential_permission ADD CONSTRAINT FK_TEAM_CREDENTIAL_PERMISSION_TEAM FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE team_credential_permission ADD CONSTRAINT FK_TEAM_CREDENTIAL_PERMISSION_CREDENTIAL FOREIGN KEY (credential_id) REFERENCES credential (id) ON DELETE CASCADE');

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql('ALTER TABLE shared_access ADD can_reveal_password BOOLEAN DEFAULT TRUE NOT NULL');
            $this->addSql('CREATE TABLE team_credential_permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, team_id INT NOT NULL, credential_id INT NOT NULL, can_reveal_password BOOLEAN DEFAULT TRUE NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_TEAM_CREDENTIAL_PERMISSION_TEAM ON team_credential_permission (team_id)');
            $this->addSql('CREATE INDEX IDX_TEAM_CREDENTIAL_PERMISSION_CREDENTIAL ON team_credential_permission (credential_id)');
            $this->addSql('CREATE UNIQUE INDEX uniq_team_credential_permission ON team_credential_permission (team_id, credential_id)');
            $this->addSql('ALTER TABLE team_credential_permission ADD CONSTRAINT FK_TEAM_CREDENTIAL_PERMISSION_TEAM FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('ALTER TABLE team_credential_permission ADD CONSTRAINT FK_TEAM_CREDENTIAL_PERMISSION_CREDENTIAL FOREIGN KEY (credential_id) REFERENCES credential (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();

        if ($platform === 'mysql') {
            $this->addSql('DROP TABLE team_credential_permission');
            $this->addSql('ALTER TABLE shared_access DROP can_reveal_password');

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql('DROP TABLE team_credential_permission');
            $this->addSql('ALTER TABLE shared_access DROP can_reveal_password');

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }
}
