<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260819170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add centralized subscription plan configuration with current Free defaults';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();
        $limits = '{"credentials":5,"shares":3,"teams":1,"extension_installations":1}';
        $features = '{"password_generator":true,"secure_notes":false,"security_checker":false,"credential_import":false}';

        if ($platform === 'mysql') {
            $this->addSql('CREATE TABLE subscription_plan_configuration (id INT AUTO_INCREMENT NOT NULL, plan_code VARCHAR(32) NOT NULL, limits JSON NOT NULL, features JSON NOT NULL, updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX uniq_subscription_plan_configuration_code (plan_code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('INSERT INTO subscription_plan_configuration (plan_code, limits, features, updated_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP)', ['free', $limits, $features]);

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql('CREATE TABLE subscription_plan_configuration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan_code VARCHAR(32) NOT NULL, limits JSON NOT NULL, features JSON NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX uniq_subscription_plan_configuration_code ON subscription_plan_configuration (plan_code)');
            $this->addSql('COMMENT ON COLUMN subscription_plan_configuration.updated_at IS \'(DC2Type:datetime_immutable)\'');
            $this->addSql('INSERT INTO subscription_plan_configuration (plan_code, limits, features, updated_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP)', ['free', $limits, $features]);

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE subscription_plan_configuration');
    }
}
