<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260820120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add idempotent Stripe webhook tracking and normalized subscription billing details';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform()->getName();

        if ($platform === 'mysql') {
            $this->addSql('ALTER TABLE user_subscription ADD stripe_price_id VARCHAR(255) DEFAULT NULL, ADD quantity INT DEFAULT 1 NOT NULL, ADD current_period_end DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD cancel_at_period_end TINYINT(1) DEFAULT 0 NOT NULL');
            $this->addSql('CREATE TABLE stripe_webhook_event (id INT AUTO_INCREMENT NOT NULL, stripe_event_id VARCHAR(255) NOT NULL, type VARCHAR(100) NOT NULL, processed_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX uniq_stripe_webhook_event_id (stripe_event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql("UPDATE subscription_plan_configuration SET limits = JSON_SET(limits, '$.credentials', 15, '$.shares', 5), updated_at = CURRENT_TIMESTAMP WHERE plan_code = 'free' AND JSON_UNQUOTE(JSON_EXTRACT(limits, '$.credentials')) = '5' AND JSON_UNQUOTE(JSON_EXTRACT(limits, '$.shares')) = '3'");

            return;
        }

        if ($platform === 'postgresql') {
            $this->addSql('ALTER TABLE user_subscription ADD stripe_price_id VARCHAR(255) DEFAULT NULL');
            $this->addSql('ALTER TABLE user_subscription ADD quantity INT DEFAULT 1 NOT NULL');
            $this->addSql('ALTER TABLE user_subscription ADD current_period_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
            $this->addSql('ALTER TABLE user_subscription ADD cancel_at_period_end BOOLEAN DEFAULT FALSE NOT NULL');
            $this->addSql('COMMENT ON COLUMN user_subscription.current_period_end IS \'(DC2Type:datetime_immutable)\'');
            $this->addSql('CREATE TABLE stripe_webhook_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stripe_event_id VARCHAR(255) NOT NULL, type VARCHAR(100) NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX uniq_stripe_webhook_event_id ON stripe_webhook_event (stripe_event_id)');
            $this->addSql('COMMENT ON COLUMN stripe_webhook_event.processed_at IS \'(DC2Type:datetime_immutable)\'');
            $this->addSql("UPDATE subscription_plan_configuration SET limits = jsonb_set(jsonb_set(limits::jsonb, '{credentials}', '15'::jsonb), '{shares}', '5'::jsonb)::json, updated_at = CURRENT_TIMESTAMP WHERE plan_code = 'free' AND limits->>'credentials' = '5' AND limits->>'shares' = '3'");

            return;
        }

        $this->abortIf(true, sprintf('Unsupported platform: %s', $platform));
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE stripe_webhook_event');
        $this->addSql('ALTER TABLE user_subscription DROP stripe_price_id, DROP quantity, DROP current_period_end, DROP cancel_at_period_end');
    }
}
